name: test-build

on: push
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps: 

      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: cd app && make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java
          with:
            coverageCommand: cd app && make report
            coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
      